Repository comphack/libcomp, pull requests merged in 2019-05, with the labels that each got.

#5 [ADD] Memory manager for diagnostic of memory leaks.
  libcomp/CMakeLists.txt
  libcomp/schema/serverconfig.xml
  libcomp/src/BaseServer.cpp
  libcomp/src/Exception.cpp
  libcomp/src/Exception.h
  libcomp/src/MemoryManager.cpp
  libcomp/src/MemoryManager.h
  libcomp/src/WindowsService.cpp
  libcomp/src/rbtree.c
  libcomp/src/rbtree.h
  standalone.cmake
Labels: enhancement

#6 [FIX] Corrected the output of CSkillData.
  libcomp/schema/binarydata/cskilldata.xml
  libobjgen/res/VariableStringSaveDynamicRound.cpp
Labels: bug

#9 Multitalk and missed values for comp_bdpatch
  libcomp/CMakeLists.txt
  libcomp/schema/action_updatepoints.xml
  libcomp/schema/binarydata/cculturedata.xml
  libcomp/schema/binarydata/cdevilboosticondata.xml
  libcomp/schema/binarydata/cmultitalkdata.xml
  libcomp/schema/binarydata/cspecialskilleffectdata.xml
  libcomp/schema/libcomp-master.xml
  libcomp/schema/spawn.xml
  standalone.cmake
Labels: bug, enhancement

#10 [ADD] New Travis CI build system for libcomp
  .travis.yml
  appveyor.yml
  ci/dropbox-deployment-1.0.0.gem
  ci/global.sh
  ci/linux-before_install.sh
  ci/linux-libcomp.sh
  ci/linux-warmcache.sh
  ci/report-progress.sh
  ci/windows-libcomp.sh
  ci/windows-warmcache.sh
Labels: enhancement

#11 [FIX] Missing dropbox_setup for the Linux build.
  ci/linux-libcomp.sh
Labels: bug

#12 [ADD] Mutex wrapper to detect errors on Linux.
  libcomp/CMakeLists.txt
  libcomp/src/Mutex.cpp
  libcomp/src/Mutex.h
Labels: enhancement

#13 [FIX] Allow documentation to be built when using a pre-built libcomp.
  CMakeLists.txt
  libcomp/doc/Doxyfile.in
Labels: bug
