Repository comphack/libcomp, pull requests merged in 2019-07, with the labels that each got.

#27 Adding DemonQuestResetTime to CharacterProgress
  libcomp/schema/character.xml
Labels: bug

#28 [FIX] AddManager
  libcomp/src/Worker.cpp
Labels: bug

#29 [ADD] mbedtls support (replaces OpenSSL on some platforms).
  libcomp/CMakeLists.txt
  libcomp/doc/MainPage.dox
  libcomp/src/BaseServer.cpp
  libcomp/src/ChannelConnection.cpp
  libcomp/src/ChannelConnection.h
  libcomp/src/Crypto.cpp
  libcomp/src/Crypto.h
  libcomp/src/DataStore.cpp
  libcomp/src/Decrypt.cpp
  libcomp/src/Decrypt.h
  libcomp/src/DefinitionManager.h
  libcomp/src/EncryptedConnection.cpp
  libcomp/src/EncryptedConnection.h
  libcomp/src/InternalConnection.cpp
  libcomp/src/InternalConnection.h
  libcomp/src/LobbyConnection.cpp
  libcomp/src/LobbyConnection.h
  libcomp/src/Randomizer.cpp
  libcomp/src/ScriptEngine.cpp
  libcomp/src/TcpConnection.cpp
  libcomp/src/TcpConnection.h
  libcomp/src/TcpServer.cpp
  libcomp/src/TcpServer.h
  libcomp/tests/Crypto.cpp
  libcomp/tests/DiffieHellman.cpp
  libcomp/tests/ScriptEngine.cpp
  libobjgen/CMakeLists.txt
  libobjgen/src/UUID.cpp
  standalone.cmake
Labels: enhancement

#31 libcomp objgen/partial enhancements
  libcomp/schema/action_updateflag.xml
  libcomp/schema/event.xml
  libcomp/schema/item.xml
  libcomp/schema/server_npc.xml
  libcomp/src/ServerDataManager.cpp
Labels: enhancement

#32 Server configurable DemonFamiliarityTypes
  libcomp/CMakeLists.txt
  libcomp/schema/demon.xml
  libcomp/src/ServerDataManager.cpp
  libcomp/src/ServerDataManager.h
Labels: bug, enhancement
